import { LLMAgent } from "../generate.js";

const STORY_GENRES = [
  "Fantasy",
  "Sci-Fi",
  "Horror",
  "Romance",
  "Mystery",
  "Thriller",
  "Historical",
  "Contemporary",
];
const STORY_TONES = [
  "Dark",
  "Light",
  "Grim",
  "Hopeful",
  "Intimate",
  "Epic",
  "Tense",
  "Whimsical",
  "Melancholic",
  "Romantic",
];

export const storyCoreParseAgent = new LLMAgent({
  role: "story metadata extractor",
  instructions:
    "Read the story text. Synthesise a concise 2-4 sentence premise (do not copy verbatim). Extract metadata only. Do NOT extract characters or locations.",
  outputShape: [
    "{",
    '  "title": "string",',
    '  "premise": "string — synthesised 2-4 sentence premise",',
    '  "genres": ["string", ...],',
    `  // allowed genres: ${STORY_GENRES.join(", ")}`,
    '  "tone": ["string", ...],',
    `  // allowed tones: ${STORY_TONES.join(", ")}`,
    '  "rules": ["string", ...],',
    '  "writingStyle": "string"',
    "}",
  ].join("\n"),
  temperature: 0.1,
  num_ctx: 8192,
});

export const storyCharactersParseAgent = new LLMAgent({
  role: "character extractor",
  instructions:
    "Extract all named characters from the story text. Use the story premise as context. Also extract the initial relationships between characters as they appear at the start of the story.",
  outputShape: [
    "{",
    '  "characters": [',
    "    {",
    '      "name": "string",',
    '      "role": "string",',
    '      "isUserPersona": false,',
    '      "age": "string",',
    '      "gender": "string",',
    '      "species": "string",',
    '      "clothing": "string",',
    '      "appearance": "string",',
    '      "personality": ["trait"],',
    '      "speechStyle": "string",',
    '      "trueMotives": "string",',
    '      "fears": ["fear"],',
    '      "relationships": [',
    "        {",
    '          "otherCharacterName": "string — must match another character\'s name exactly",',
    '          "emotion": "string — e.g. love, fear, rivalry, ally, hate, distrust, respect, neutral",',
    '          "publicAttitude": "string — how they visibly act toward this character",',
    '          "privateAttitude": "string — their hidden feelings toward this character",',
    '          "trustLevel": 5',
    "          // trustLevel 0-10: 0=no trust, 5=neutral, 10=complete trust",
    "        }",
    "      ]",
    "      // omit relationships array if the character has no notable relationships",
    "    }",
    "  ]",
    "}",
  ].join("\n"),
  temperature: 0.1,
  num_ctx: 8192,
});

export const storyLocationsParseAgent = new LLMAgent({
  role: "location extractor",
  instructions:
    "Extract all distinct locations and settings from the story text. Use the story premise as context.",
  outputShape: [
    "{",
    '  "locations": [',
    "    {",
    '      "name": "string",',
    '      "description": "string",',
    '      "layout": "string",',
    '      "lighting": "string",',
    '      "atmosphere": "string",',
    '      "soundscape": "string",',
    '      "smells": "string",',
    '      "notes": "string",',
    '      "tags": ["string"]',
    "    }",
    "  ]",
    "}",
  ].join("\n"),
  temperature: 0.1,
  num_ctx: 8192,
});

export const storyMemoriesParseAgent = new LLMAgent({
  role: "story event extractor",
  instructions:
    "Read the story text and extract key story events/turning points for each named character, in chronological order. For each event, also note any character trait changes (deltas) that resulted from it. Include 3-8 events per character; only include events with importance >= 0.4. Interleave characters naturally in timeline order.",
  outputShape: [
    "{",
    '  "memories": [',
    "    {",
    '      "characterName": "string — must match one of the provided character names",',
    '      "summary": "string — one sentence describing what happened to this character",',
    '      "tags": ["string"],',
    '      "importance": 0.0,',
    "      // importance 0.0–1.0: 0.9+ for major turning points, 0.6 for significant events, 0.4 for minor events",
    '      "deltas": {',
    "        // omit entire deltas object if no trait or relationship changes occurred",
    '        "personality": { "add": ["new trait"], "remove": ["lost trait"] },',
    '        "fears": { "add": ["new fear"], "remove": ["resolved fear"] },',
    '        "speechStyle": "new speech style if changed, otherwise omit",',
    '        "appearance": "new appearance if changed, otherwise omit",',
    '        "clothing": "new clothing if changed, otherwise omit",',
    '        "relationships": [',
    "          {",
    '            "otherCharacterName": "string — name of the other character involved",',
    '            "emotion": "string — e.g. love, fear, betrayal, ally, hate, distrust, respect",',
    '            "publicAttitude": "string — how they now visibly act toward this character",',
    '            "privateAttitude": "string — their hidden feelings after this event",',
    '            "trustLevel": 5',
    "          }",
    "        ]",
    "        // include relationships only if this event changed how the character feels about another",
    "      }",
    "    }",
    "  ]",
    "  // ordered chronologically: earliest event first",
    "}",
  ].join("\n"),
  temperature: 0.1,
  num_ctx: 8192,
});

export const legacyParseAgent = new LLMAgent({
  role: "story metadata extractor",
  instructions:
    "Read the provided story text. Synthesise a concise 2-4 sentence premise (do not copy verbatim). Extract characters and locations.",
  outputShape: [
    "{",
    '  "title": "string",',
    '  "premise": "string — synthesised 2-4 sentence premise",',
    '  "genres": ["string", ...],',
    `  // allowed genres: ${STORY_GENRES.join(", ")}`,
    '  "tone": ["string", ...],',
    `  // allowed tones: ${STORY_TONES.join(", ")}`,
    '  "rules": ["string", ...],',
    '  "writingStyle": "string",',
    '  "characters": [',
    "    {",
    '      "name": "string",',
    '      "role": "string",',
    '      "isUserPersona": false,',
    '      "age": "string",',
    '      "gender": "string",',
    '      "species": "string",',
    '      "clothing": "string",',
    '      "appearance": "string",',
    '      "personality": ["trait"],',
    '      "speechStyle": "string",',
    '      "trueMotives": "string",',
    '      "fears": ["fear"]',
    "    }",
    "  ],",
    '  "locations": [',
    "    {",
    '      "name": "string",',
    '      "description": "string",',
    '      "layout": "string",',
    '      "lighting": "string",',
    '      "atmosphere": "string",',
    '      "soundscape": "string",',
    '      "smells": "string",',
    '      "notes": "string",',
    '      "tags": ["string"]',
    "    }",
    "  ]",
    "}",
  ].join("\n"),
  temperature: 0.1,
  num_ctx: 8192,
});
