import { STORY_GENRES, STORY_TONES } from "../features/stories/index.js";
import { LLMAgent } from "../generate.js";

export const legacyParseAgent = new LLMAgent({
  role: "story metadata extractor",
  instructions:
    "Read the provided story text. Synthesise a concise 2-4 sentence premise (do not copy verbatim). Extract characters and locations.",
  outputShape: [
    "{",
    '  "title": "string",',
    '  "premise": "string — synthesised 2-4 sentence premise",',
    '  "genres": ["string", ...],',
    `  // allowed genres: ${STORY_GENRES.join(", ")}`,
    '  "tone": ["string", ...],',
    `  // allowed tones: ${STORY_TONES.join(", ")}`,
    '  "rules": ["string", ...],',
    '  "writingStyle": "string",',
    '  "characters": [',
    "    {",
    '      "name": "string",',
    '      "role": "string",',
    '      "isUserPersona": false,',
    '      "age": "string",',
    '      "gender": "string",',
    '      "species": "string",',
    '      "clothing": "string",',
    '      "appearance": "string",',
    '      "personality": ["trait"],',
    '      "speechStyle": "string",',
    '      "trueMotives": "string",',
    '      "fears": ["fear"]',
    "    }",
    "  ],",
    '  "locations": [',
    "    {",
    '      "name": "string",',
    '      "description": "string",',
    '      "layout": "string",',
    '      "lighting": "string",',
    '      "atmosphere": "string",',
    '      "soundscape": "string",',
    '      "smells": "string",',
    '      "notes": "string",',
    '      "tags": ["string"]',
    "    }",
    "  ]",
    "}",
  ].join("\n"),
  temperature: 0.1,
  num_ctx: 8192,
});
