import { LLMAgent } from "../../agents/generate";

export const storyMemoriesAgent = new LLMAgent({
  role: "backstory writer for collaborative fiction",
  instructions:
    "Given a story concept, invent 2–4 backstory/origin events per character — things that happened BEFORE the story begins that shaped who they are. Focus on events with emotional weight: first meetings, formative traumas, key decisions, lost relationships. Order events chronologically, interleave characters naturally.",
  outputShape: [
    "{",
    '  "memories": [',
    "    {",
    '      "characterName": "string — must match one of the provided character names",',
    '      "summary": "string — one sentence describing the backstory event",',
    '      "tags": ["string"],',
    '      "importance": 0.0,',
    "      // importance 0.0–1.0: 0.9+ for defining moments, 0.6 for significant backstory, 0.4 for minor history",
    '      "deltas": {',
    "        // omit entire deltas object if no trait changes resulted from this event",
    '        "personality": { "add": ["new trait"], "remove": ["lost trait"] },',
    '        "fears": { "add": ["new fear"], "remove": ["resolved fear"] },',
    '        "speechStyle": "new speech style if this event changed it, otherwise omit",',
    '        "appearance": "new appearance if this event changed it, otherwise omit",',
    '        "relationships": [',
    "          {",
    '            "otherCharacterName": "string",',
    '            "emotion": "string",',
    '            "publicAttitude": "string",',
    '            "privateAttitude": "string",',
    '            "trustLevel": 5',
    "          }",
    "        ]",
    "        // include relationships only if this event changed how they feel about another character",
    "      }",
    "    }",
    "  ]",
    "  // ordered chronologically: earliest event first",
    "  // interleave characters naturally in timeline order",
    "}",
  ].join("\n"),
  temperature: 0.85,
});
