import { LLMAgent } from "../../agents/generate";

export const storyMemoriesParseAgent = new LLMAgent({
  role: "story event extractor",
  instructions: [
    "Read the story text and extract key story events/turning points for each named character, in chronological order (earliest event first, storyOrder starting at 1). Include 3-8 events per character; only include events with importance >= 0.4. Interleave characters naturally in timeline order.",
    "importance is a float 0.0–1.0: use 0.9+ for major turning points, 0.7 for character-defining events, 0.4-0.69 for plot events.",
    "sceneId is the name of the scene or act this event belongs to (use the scene delimiter text if present).",
    "For effects: list only fields that CHANGED as a result of this event, using the exact dot-path (e.g. public.personality, private.hiddenEmotionalState, private.fears, relationships). Use op 'add' or 'remove' for arrays, 'set' for strings. Omit effects entirely if nothing changed.",
    "entityType is always 'character'. targetId is only needed for relationship path effects.",
  ].join(" "),
  outputShape: [
    "{",
    '  "memories": [',
    "    {",
    '      "characterName": "string — must match one of the provided character names",',
    '      "summary": "string — one sentence describing what happened to this character",',
    '      "tags": ["string"],',
    '      "importance": 0.0,',
    '      "sceneId": "string — scene name, or null",',
    '      "storyOrder": 1,',
    '      "effects": [',
    "        {",
    '          "path": "public.personality",',
    '          "op": "add",',
    '          "value": "new trait",',
    '          "weight": 1,',
    '          "entityType": "character"',
    "        },",
    "        {",
    '          "path": "private.hiddenEmotionalState",',
    '          "op": "set",',
    '          "value": "description of new emotional state"',
    "        }",
    "      ]",
    "    }",
    "  ]",
    "}",
  ].join("\n"),
  temperature: 0.1,
  num_ctx: 8192,
});
