import { LLMAgent } from "../../generate";

export const storyMemoriesParseAgent = new LLMAgent({
  role: "story event extractor",
  instructions:
    "Read the story text and extract key story events/turning points for each named character, in chronological order. For each event, also note any character trait changes (deltas) that resulted from it. Include 3-8 events per character; only include events with importance >= 0.4. Interleave characters naturally in timeline order.",
  outputShape: [
    "{",
    '  "memories": [',
    "    {",
    '      "characterName": "string — must match one of the provided character names",',
    '      "summary": "string — one sentence describing what happened to this character",',
    '      "tags": ["string"],',
    '      "importance": 0.0,',
    "      // importance 0.0–1.0: 0.9+ for major turning points, 0.6 for significant events, 0.4 for minor events",
    '      "deltas": {',
    "        // omit entire deltas object if no trait or relationship changes occurred",
    '        "personality": { "add": ["new trait"], "remove": ["lost trait"] },',
    '        "fears": { "add": ["new fear"], "remove": ["resolved fear"] },',
    '        "speechStyle": "new speech style if changed, otherwise omit",',
    '        "appearance": "new appearance if changed, otherwise omit",',
    '        "clothing": "new clothing if changed, otherwise omit",',
    '        "relationships": [',
    "          {",
    '            "otherCharacterName": "string — name of the other character involved",',
    '            "emotion": "string — e.g. love, fear, betrayal, ally, hate, distrust, respect",',
    '            "publicAttitude": "string — how they now visibly act toward this character",',
    '            "privateAttitude": "string — their hidden feelings after this event",',
    '            "trustLevel": 5',
    "          }",
    "        ]",
    "        // include relationships only if this event changed how the character feels about another",
    "      }",
    "    }",
    "  ]",
    "  // ordered chronologically: earliest event first",
    "}",
  ].join("\n"),
  temperature: 0.1,
  num_ctx: 8192,
});
