import { LLMAgent } from "../../generate";

export const storyCharactersParseAgent = new LLMAgent({
  role: "character extractor",
  instructions:
    "Extract all named characters from the story text. Use the story premise as context. Also extract the initial relationships between characters as they appear at the start of the story.",
  outputShape: [
    "{",
    '  "characters": [',
    "    {",
    '      "name": "string",',
    '      "role": "string",',
    '      "isUserPersona": false,',
    '      "age": "string",',
    '      "gender": "string",',
    '      "species": "string",',
    '      "clothing": "string",',
    '      "appearance": "string",',
    '      "personality": ["trait"],',
    '      "speechStyle": "string",',
    '      "trueMotives": "string",',
    '      "fears": ["fear"],',
    '      "relationships": [',
    "        {",
    '          "otherCharacterName": "string — must match another character\'s name exactly",',
    '          "emotion": "string — e.g. love, fear, rivalry, ally, hate, distrust, respect, neutral",',
    '          "publicAttitude": "string — how they visibly act toward this character",',
    '          "privateAttitude": "string — their hidden feelings toward this character",',
    '          "trustLevel": 5',
    "          // trustLevel 0-10: 0=no trust, 5=neutral, 10=complete trust",
    "        }",
    "      ]",
    "      // omit relationships array if the character has no notable relationships",
    "    }",
    "  ]",
    "}",
  ].join("\n"),
  temperature: 0.1,
  num_ctx: 8192,
});
