import { createPromptRunner } from "../../LLM/prompt-runners/create-prompt-runner";

export const storyCharactersParseAgent = createPromptRunner({
  role: "character extractor",
  instructions:
    "Extract all named characters from the story text. Use the story premise as context. Also extract the initial relationships between characters as they appear at the start of the story. trustLevel is an integer 0–10 (0=no trust, 5=neutral, 10=complete trust). Omit the relationships array entirely if the character has no notable relationships.",
  outputShape: [
    "{",
    '  "characters": [',
    "    {",
    '      "name": "string",',
    '      "role": "string",',
    '      "isUserPersona": false,',
    '      "age": "string",',
    '      "gender": "string",',
    '      "species": "string",',
    '      "clothing": "string",',
    '      "appearance": "string",',
    '      "personality": ["trait"],',
    '      "speechStyle": "string",',
    '      "trueMotives": "string",',
    '      "fears": ["fear"],',
    '      "relationships": [',
    "        {",
    '          "otherCharacterName": "string — must match another character\'s name exactly",',
    '          "emotion": "string — e.g. love, fear, rivalry, ally, hate, distrust, respect, neutral",',
    '          "publicAttitude": "string — how they visibly act toward this character",',
    '          "privateAttitude": "string — their hidden feelings toward this character",',
    '          "trustLevel": 5',
    "        }",
    "      ]",
    "    }",
    "  ]",
    "}",
  ].join("\n"),
  temperature: 0.1,
  num_ctx: 8192,
});

export const characterDeepDiveAgent = createPromptRunner({
  role: "character analyst",
  instructions: [
    "You are given a complete story text and a single character name. Extract EVERYTHING the text reveals about that character.",
    "Do not write 'Unknown'. If it is in the text, extract it.",
    "For identities: list each distinct form or persona the character has (e.g. human disguise vs true form).",
    "selfAware is true if the character knows about that identity.",
    "linkedCharacterNames lists other character names who are the same entity at a different point in time or under a different name.",
    "Only include linkedCharacterNames if the text explicitly confirms the link.",
    "Personality, fears, and privateKnowledge reflect the character AT THE START of the story (before any events change them).",
  ].join(" "),
  outputShape: [
    "{",
    '  "name": "string",',
    '  "role": "string",',
    '  "age": "string",',
    '  "gender": "string",',
    '  "species": "string",',
    '  "clothing": "string — appearance at story start",',
    '  "appearance": "string — 2-3 sentences",',
    '  "personality": ["trait — evidenced in text"],',
    '  "speechStyle": "string",',
    '  "trueMotives": "string",',
    '  "fears": ["fear — shown in action"],',
    '  "moralLimits": "string",',
    '  "hiddenEmotionalState": "string — at story start",',
    '  "privateKnowledge": ["fact this character knows that others do not"],',
    '  "identities": [',
    "    {",
    '      "name": "string — name of this form/persona",',
    '      "appearance": "string",',
    '      "abilities": ["string"],',
    '      "selfAware": true,',
    '      "knownBy": ["other character names aware of this identity"],',
    '      "conditions": "string — when/how this identity manifests",',
    '      "notes": "string"',
    "    }",
    "  ],",
    '  "linkedCharacterNames": ["string — other character names who are the same entity"]',
    "}",
  ].join("\n"),
  temperature: 0.2,
  num_ctx: 8192,
});
